export const colors = [
    { id: 1, name: 'Beige' },
    { id: 2, name: 'Beige and Black' },
    { id: 3, name: 'Beige and Olive' },
    { id: 4, name: 'Black' },
    { id: 5, name: 'Black and Blue' },
    { id: 6, name: 'Black and White' },
    { id: 7, name: 'Blue ' },
    { id: 8, name: 'Blue and Green' },
    { id: 9, name: 'Blue and Pink' },
    { id: 10, name: 'Blue and White' },
    { id: 11, name: 'Blue and Yellow' },
    { id: 12, name: 'Blue, Grey and White' },
    { id: 13, name: 'Blue, Pink and White' },
    { id: 14, name: 'Bottle Green' },
    { id: 15, name: 'Brown' },
    { id: 16, name: 'Brown and Yellow' },
    { id: 17, name: ' Green' },
    { id: 18, name: 'Grey' },
    { id: 19, name: 'Grey and Red' },
    { id: 21, name: 'Ivory' },
    { id: 22, name: 'Light Blue and White' },
    { id: 23, name: 'Marroon' },
    { id: 24, name: 'Multicolor' },
    { id: 25, name: 'Navy Blue' },
    { id: 26, name: 'Olive' },
    { id: 27, name: 'Olive Green' },
    { id: 28, name: 'Olive, Brown and Blue' },
    { id: 29, name: 'Orange' },
    { id: 30, name: 'Peach' },
    { id: 32, name: 'Pink' },
    { id: 33, name: 'Pink and Olive' },
    { id: 34, name: 'Pink and Yellow' },
    { id: 35, name: 'Red' },
    { id: 36, name: 'Red and White' },
    { id: 37, name: 'Rust' },
    { id: 38, name: 'Rust and White' },
    { id: 39, name: 'White and Green' },
    { id: 40, name: 'White and Orange' },
    { id: 41, name: 'White and Red' },
    { id: 42, name: 'White and Yellow' },
    { id: 43, name: 'Yellow' },
]

export const sizes = [
    { id: 1, name: '2-3 Yrs' },
    { id: 2, name: '3-4 Yrs' },
    { id: 3, name: '4-5 Yrs' },
    { id: 4, name: '5-6 Yrs' },
    { id: 5, name: '6-7 Yrs' },
    { id: 6, name: '7-8 Yrs' },
]

export const boysItems = [
    { label: 'All Boys', key: '1' },
    { label: 'PlaySuits and Playsets', key: '2' },
    { label: 'Shirts', key: '3' },
    { label: 'Winter Wear', key: '4' },
]

export const girlsItems = [
    { label: 'All Girls', key: '1' },
    { label: 'PlaySuits and Playsets', key: '2' },
    { label: 'Dresses', key: '3' },
    { label: 'Winter Wear', key: '4' },
]

export const shoppingData = [
    { id: 1, imageUrl: '/kid4.jpg', altText: 'KidImages' },
    { id: 2, imageUrl: '/kid4.jpg', altText: 'KidImages' },
    { id: 3, imageUrl: '/kid4.jpg', altText: 'KidImages' },
    { id: 4, imageUrl: '/kid4.jpg', altText: 'KidImages' },
    { id: 5, imageUrl: '/kid4.jpg', altText: 'KidImages' },
    { id: 6, imageUrl: '/kid4.jpg', altText: 'KidImages' },
    { id: 7, imageUrl: '/kid4.jpg', altText: 'KidImages' },
    { id: 8, imageUrl: '/kid4.jpg', altText: 'KidImages' },
]

export const images = [
    { id: 1, imgUrl: 'https://swiperjs.com/demos/images/nature-1.jpg' },
    { id: 2, imgUrl: 'https://swiperjs.com/demos/images/nature-2.jpg' },
    { id: 3, imgUrl: 'https://swiperjs.com/demos/images/nature-3.jpg' },
    { id: 4, imgUrl: 'https://swiperjs.com/demos/images/nature-4.jpg' },
    { id: 5, imgUrl: 'https://swiperjs.com/demos/images/nature-5.jpg' },
    { id: 6, imgUrl: 'https://swiperjs.com/demos/images/nature-6.jpg' },
    { id: 7, imgUrl: 'https://swiperjs.com/demos/images/nature-7.jpg' },
    { id: 8, imgUrl: 'https://swiperjs.com/demos/images/nature-8.jpg' },
    { id: 9, imgUrl: 'https://swiperjs.com/demos/images/nature-9.jpg' },
    { id: 10, imgUrl: 'https://swiperjs.com/demos/images/nature-10.jpg' },
]
